### ISSUE TITLE
我来说下遇到的问题，也防止后面使用的兄弟遇雷

### ISSUE THREAD

**Issue by Winyer** [Flying-Tom/QzoneLike#3]
我来说下遇到的问题，也防止后面使用的兄弟遇雷
第一个，这不是Windwos下使用的，是Linux！！！！（估计也只有我看都不看就在Win10准备跑了吧）
第二个，pip必须是最新版本，否则会失败，而且python 2.7也跑不起来
第三个，如果like.py出现编码错误请在百度搜索加上UTF-8的那个编码
第四个，第四个我也没解决，所以现在还是没能运行起来......
把第四个的log附在下面吧

nohup: ignoring input
2022-09-05 02:23:36,086 - like.py[line:16] - INFO: Start logging
2022-09-05 02:23:36,086 - like.py[line:26] - INFO: Chrome already installed
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
2022-09-05 02:23:36,094 - like.py[line:48] - INFO: No running chrome instance now
2022-09-05 02:23:37,597 - patcher.py[line:231] - INFO: patching driver executable /root/.local/share/undetected_chromedriver/7ad013a392ea6ffc_chromedriver
Traceback (most recent call last):
  File "like.py", line 83, in <module>
    driver = init_driver()
  File "like.py", line 37, in init_driver
    driver = uc.Chrome(options=options, version_main=98)
  File "/usr/local/lib/python3.7/site-packages/undetected_chromedriver/__init__.py", line 408, in __init__
    keep_alive=keep_alive,
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 72, in __init__
    service_log_path, service, keep_alive)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chromium/webdriver.py", line 97, in __init__
    options=options)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/undetected_chromedriver/__init__.py", line 590, in start_session
    capabilities, browser_profile
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:48211
from session not created: This version of ChromeDriver only supports Chrome version 98
Current browser version is 105.0.5195.102
Stacktrace:
#0 0x555bec291b33 <unknown>
#1 0x555bebd5a6d8 <unknown>
#2 0x555bebd813a5 <unknown>
#3 0x555bebd78c76 <unknown>
#4 0x555bebdb3e0a <unknown>
#5 0x555bebdadf53 <unknown>
#6 0x555bebd83a0a <unknown>
#7 0x555bebd84ad5 <unknown>
#8 0x555bec2c32fd <unknown>
#9 0x555bec2dc4bb <unknown>
#10 0x555bec2c50d5 <unknown>
#11 0x555bec2dd145 <unknown>
#12 0x555bec2b8aaf <unknown>
#13 0x555bec2f9ba8 <unknown>
#14 0x555bec2f9d28 <unknown>
#15 0x555bec31448d <unknown>
#16 0x7fd42dfb36db <unknown>

**Comment by Flying-Tom** [comment]
chrome 版本与 undetected_chromedriver 对不上 （当时不知道为什么硬编码了一个 version_main=98）
